// Full text of the Beta Tester Non-Disclosure Agreement, shown in
// NdaModal before account creation. Keep this in sync with the source
// legal document -- it's rendered verbatim, paragraph by paragraph.
export const NDA_TITLE = "Beta Tester Non-Disclosure Agreement";

export const NDA_PARAGRAPHS: string[] = [
  "This Agreement is made between Audition with Me LLC, a New York State LLC (“Company”), and you (“Tester”). Company is developing a pre-release application and website known as Audition with Me that incorporates artificial intelligence features (the “Platform”), and will give Tester early access to evaluate it and provide feedback (the “Beta Program”). In consideration of that access, the Parties agree:",
  "1. Confidential Information. All non-public information Tester receives, observes, or learns in connection with the Beta Program, whether or not marked confidential, including the Platform’s features, interface, functionality, capabilities, and limitations; the AI models, system prompts, guardrails, and their behavior; Outputs; code, architecture, and technical documentation; bugs, defects, and security vulnerabilities; roadmaps, release dates, and pricing; credentials and test builds; the identity of other testers; the existence of the Platform and the Beta Program; and Tester’s own notes, screenshots, and recordings reflecting any of the foregoing.",
  "2. Access. Company grants Tester a personal, revocable, non-transferable right to use the Platform solely to evaluate it and provide feedback. Credentials are personal to Tester and may not be shared. The Platform is pre-release, may contain errors, and may be changed, suspended, or discontinued at any time.",
  "3. Confidentiality. Tester will hold Confidential Information in strict confidence, use it only for the Beta Program, and protect it with at least reasonable care. Without Company’s prior written consent, Tester will not disclose it to anyone; post, review, describe, stream, or discuss the Platform on social media or any other public or semi-public channel; share screenshots, recordings, or Outputs with third parties; or speak about the Platform to press, analysts, or competitors. Screenshots and recordings made solely for bug reports sent to Company are permitted. Tester will notify Company within 24 hours of any suspected unauthorized disclosure.",
  "4. No Third-Party AI Tools. Tester will not enter or upload any Confidential Information, including Outputs, screenshots, or descriptions of the Platform, into any third-party AI tool, chatbot, or transcription or note-taking service not provided by Company.",
  "5. AI-Specific Restrictions. Tester will not: (a) reverse engineer or attempt to derive the Platform’s source code, model weights, training data, or system prompts; (b) use the Platform, inputs, or Outputs to train, fine-tune, distill, or benchmark any other AI model, product, or service; (c) publish benchmark or comparative test results; (d) circumvent or defeat any security feature, content filter, or safety guardrail, including by jailbreaking or prompt injection, except as Company authorizes in writing; (e) use automated means to access or extract data from the Platform; or (f) submit inputs or generate Outputs that infringe third-party rights, replicate any real person’s likeness or voice without authorization, sexualize minors, or are otherwise unlawful.",
  "6. Security and Safety Reporting. If Tester discovers a security vulnerability, data exposure, or guardrail failure, Tester will stop immediately, report it to Company within 24 hours, not further exploit or disclose it, and delete any other user’s data inadvertently accessed.",
  "7. Data. Tester warrants Tester has the rights to submit all information and data. Tester will not submit government ID or financial account numbers, health or biometric data, or another person’s personal information without authorization. Company may host, process, and analyze inputs, Outputs, and usage data to operate, debug, secure, and evaluate the Platform. Training: Company may use inputs, Outputs, and usage data to train and improve the Platform’s AI features. As between the Parties, Company owns all Outputs and Data subject to the confidentiality obligations above. Outputs and Data may not be unique and may not be protectable by copyright.",
  "8. Telemetry and Recording. The Platform automatically collects device, usage, and session data, including inputs and Outputs. Company will use recordings only for internal research and product development. Company will not use Tester’s name, image, likeness, or voice for marketing, or to train any AI model or digital replica of Tester, without Tester’s separate written consent.",
  "9. Feedback. Tester assigns to Company all rights in feedback Tester submits and grants Company a perpetual, irrevocable, royalty-free, sublicensable license to use it in the Platform and all improvements, including those based on feedback; no other license is granted.",
  "10. Exclusions and Protected Disclosures. Confidentiality does not apply to information that is or becomes public through no fault of Tester, was lawfully known to Tester beforehand, is lawfully received from a third party without restriction, or is independently developed without reference to Confidential Information. If compelled by law, Tester will, if permitted, notify Company promptly and disclose only what is required. Nothing here limits Tester from reporting possible legal violations to, or participating in an investigation by, any government agency, or from testifying truthfully. Under 18 U.S.C. § 1833(b), Tester is not liable under any trade secret law for disclosing a trade secret in confidence to a government official or attorney solely to report a suspected violation of law, or in a filing made under seal.",
  "11. No Warranty; Limitation of Liability. THE PLATFORM AND ALL OUTPUTS ARE PROVIDED “AS IS,” WITH ALL FAULTS, AND COMPANY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY. OUTPUTS MAY BE INACCURATE, BIASED, OR OFFENSIVE, AND ARE NOT PROFESSIONAL ADVICE. COMPANY WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OR LOST DATA OR PROFITS, AND ITS TOTAL LIABILITY WILL NOT EXCEED THE GREATER OF US $100 OR AMOUNTS PAID TO TESTER.",
  "12. Term; Return. Company may terminate Tester’s access at any time, with or without cause. Confidentiality obligations continue for FIVE YEARS after termination, and for as long as the information remains a trade secret. Within 10 days after termination or on request, Tester will stop using the Platform, delete all builds, credentials, screenshots, recordings, notes, and Outputs (other than Outputs Tester is permitted to keep), and certify deletion in writing if asked.",
  "13. Publicity. Tester will not identify Tester as a beta participant or comment publicly on the Platform until public launch without Company’s written consent. If Tester makes an authorized public statement about the Platform after receiving compensation or free access, Tester will disclose that relationship as required by 16 C.F.R. Part 255.",
  "14. Remedies; Governing Law. Breach of Sections 1 and 3 through 7 would cause irreparable harm, and Company may seek injunctive relief in addition to other remedies. The prevailing Party in any action to enforce this Agreement may recover reasonable attorneys’ fees and costs. This Agreement is governed by the laws of the State of New York, without regard to conflict-of-laws rules, and the Parties submit to the exclusive jurisdiction of the state and federal courts in New York County, NY. EACH PARTY WAIVES ANY RIGHT TO TRIAL BY JURY.",
  "15. General. Tester is at least 18, has capacity to sign, is not bound by any conflicting obligation, and is not affiliated with a competitor of Company except as disclosed in writing. Tester is an independent participant, not an employee or agent, and participates without compensation. This Agreement is the entire agreement on its subject matter, controls over any click-through terms presented in the Platform, may be amended only in a signed writing, and binds permitted successors and assigns. If any provision is unenforceable, it will be modified to the minimum extent necessary, and the rest will remain in effect. This Agreement may be accepted electronically, including by clicking to accept below.",
];
